version: '3'
services:
  mc-server:
    image: mc-server
    container_name: mc-server
    ports:
      - "25565:25565"
    volumes:
      - "${SERVER_DIR-./mc}:/opt/minecraft/server:z"
    env_file: .env
    stop_grace_period: 1m30s
